### ISSUE TITLE
Number of hit squids should be a set of buttons, radio buttons etc

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#10]
Currently the drop down interface is used for number of ships eliminated, but that isn't very ergonomic in a speedrun setting. Possible interfaces:

1) radio buttons
2) set of large buttons for 1, 2, 3
3) single button that can be used to increment up/ down

**Comment by kwando1313** [comment]
I'll take this one!

**Comment by kwando1313** [comment]
nvm, @petersn has already started working on it (as per Discord messages), so I'll let him do that :P

**Comment by petersn** [comment]
I added a keyboard shortcut for incrementing the kill count. Do we think this is good enough?

**Comment by csunday95** [comment]
Is there also a key to decrement in case of a mistake?

**Comment by kwando1313** [comment]
I don't think there's a decrement yet. I think we should add a decrement as well.

**Comment by csunday95** [comment]
increment kills keyboard shortcut added in b8852151e6351a809ef7727a44a8efeacd3a7267
