### ISSUE TITLE
doComputation() generates TypeError in non-turboBlurboMode

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#23]
The `sendSpywareEvent()` call on [App.js:893][1] makes use of `gameHistoryArguments` at [App.js:901][2], which is `null` if not in `turboBlurboMode`. This results in 

```
TypeError: u is null
```

[1]: https://github.com/petersn/web-sploosh-kaboom/blob/master/src/App.js#L893
[2]: https://github.com/petersn/web-sploosh-kaboom/blob/master/src/App.js#L901

**Comment by csunday95** [comment]
`sendSpywareEvent()` can produce another `TypeError` if a user attempts to use `Copy to History` on the first board. The following procedure can reproduce the error:

1) Initialize turboblurbo mode, but not timer mode
2) fill out a game using hits/ misses in the main probability screen 
3) attempt to use the `Copy to History` button

**Comment by Amphitryon0** [comment]
The original error is fixed, and I couldn't reproduce the second error on the latest build, so I'm assuming it's fixed as well.
