### ISSUE TITLE
User controlled timer to indicate amount of time between games

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#3]
this will allow more accurate estimation of offsets between games, allowing for a smaller error margin. Also obviate the need for manual entry of the offset

**Comment by csunday95** [comment]
Maximum accuracy can be achieved with multiple splits. If the time "in-game" of sploosh and the time "out of game" can be as the RNG tick rates are different.

**Comment by petersn** [comment]
I'm currently working on this. I manually transcribed several runs, and found that it agreed with @CryZe and @csunday95's observations in TWW SD from emulation:

![image](https://user-images.githubusercontent.com/214862/80290444-d9f65680-86f9-11ea-8cce-c006bf31d86f.png)

The current rough heuristic I'm going with is:

`steps_advanced = 156 + 252 * seconds_elapsed - 940 * was_door_opened + 760 * rewards_received`

For now I'm choosing not to have little splits for "talking to Salvatore" vs "playing the board", and I'm just assuming that the runner will mash through Salvatore and rewards as quickly as possible, and therefore hopefully those events will cause a relatively consistent delta in RNG steps.

**Comment by csunday95** [comment]
given the success linkus was having with even very lenient stddev values, I imagine this will be sufficient

**Comment by csunday95** [comment]
implemented in 40d7c7e7aafa39f2ea5fc1d30b981c4b58841771
