### ISSUE TITLE
Contributing Through Discord

### ISSUE THREAD

**Issue by andrewpollack** [petersn/web-sploosh-kaboom#37]
Hello,
Apologies if this isn’t the correct channel for communication, but I’d love to learn more about contributing to this project. Is the discord channel still existent/active for development?

**Comment by csunday95** [comment]
The discord channel has been archived for some time, so the main channel for contribution is here at the repository. Issues and PR's are appreciated! You can also contact me directly on discord if you have questions (csunday95#4207)
