### ISSUE TITLE
Ship position entry streamlining 

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#4]
So far there are two suggestions for streamlined ship position entry:

1) Dragging from end to end the position of a ship

2) clicking on the square at one end of a ship and clicking on the square at the other end

both possibilities have the advantage of removing the need to identify which ship (2, 3, 4) is at a particular entry, and reducing the overall number of clicks.

**Comment by csunday95** [comment]
Currently @petersn is working on this

**Comment by petersn** [comment]
I implemented the click on both ends version -- it seems a little easier than dragging, and also is more mobile/tablet/touch screen friendly.
