### ISSUE TITLE
Sequence-agnostic modes eventually crash

### ISSUE THREAD

**Issue by Amphitryon0** [petersn/web-sploosh-kaboom#41]
After using practice mode for a while, the app crashed, which turned out to be very consistent in both Calculator Mode and Practice Mode, but not in Turbo Blurbo Mode. It appears to be caused by a memory leak. Each computation gradually increases the memory usage as seen in Task Manager. The error printed to the console about the crash is "Uncaught (in promise) RuntimeError: unreachable executed" at sploosh_wasm_bg.wasm:26231:1.

The visual effects of this bug differ between browsers. In Firefox, the board probabilities freeze at their current state, even after you hit reset. In Chrome, the probabilities will be crazy numbers for a short while, then all 100%.
![Firefox after reset](https://user-images.githubusercontent.com/17864580/116066111-51343280-a64d-11eb-9191-694ef1df44ed.png)
![Chrome after reset](https://user-images.githubusercontent.com/17864580/116066642-e20b0e00-a64d-11eb-8038-d0986428355d.png)

I can reproduce 100% consistently on multiple browsers on my machine with the following steps:
1. Load the page and switch to Practice Mode.
2. Press z 64 times, then press reset. This is one iteration.
3. Complete step 2 5 more times, for a total of 6 iterations.
4. Press z 47 times. On the 47th press and any thereafter, the bug will happen.

My theory is that wee_alloc is to blame. 437 * 604584 * 8 is suspiciously close to 2^31, and this coincides with my inability to reproduce in Turbo Blurbo Mode, as calculate_probabilities_from_game_history() does not allocate nearly as much as calculate_probabilities_with_board_constraints(). Furthermore, safe Rust on its own shouldn't really be able to leak memory. You may find you can fix this by making board_priors an array instead of a vector, but if wee_alloc is, in effect, leaking memory, it would be best to change the allocator.

**Comment by petersn** [comment]
Thanks so much for this careful investigation and steps to reproduce! I personally probably won't have a moment to investigate this for a few days, but either I or @csunday95 will definitely look into this.

**Comment by CryZe** [comment]
This looks like a wasm-bindgen bug to me. The JS glue code allocates memory for to pass the numbers into the WASM, but neither the WASM (as it doesn't take ownership) nor the glue code free that memory.
