### ISSUE TITLE
Game board hit/miss entry streamlining 

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#5]
Currently click/ double click is used to indicate to the application game progression on a particular square (hit/miss). Since user of the program will most likely be picking the recommended highest odd space each time, a streamlined input could involve either

1) keyboard shortcut for hit/miss

2) buttons for hit/miss on the suggested square

**Comment by ShayRomayo** [comment]
Currently working on this

**Comment by petersn** [comment]
Sorry for the delay in commenting here - there are keyboard shortcuts for hit/miss on the highlighted square now. Do we maybe still want left/right click for hit and miss on the board possibly?

**Comment by csunday95** [comment]
closing issue due to outstanding implementation being generally accepted as sufficient
