### ISSUE TITLE
website says impossible but "ingame" it is possible

### ISSUE THREAD

**Issue by Natives3000** [petersn/web-sploosh-kaboom#50]
![image](https://user-images.githubusercontent.com/42712457/133883818-19f4f74c-7f8d-4b43-be57-549a1a7dcd34.png)

**Comment by westim** [comment]
Your board does not match the website entries: you haven't marked enough HIT spaces to eliminate the 4-length squid, so your board contradicts the "Number of squids killed" dropdown. Specifically, the rightmost column is missing a HIT and the MISS is placed one space too low.

Here is the layout matching the game:

![image](https://user-images.githubusercontent.com/11410900/144492051-17aa632a-66eb-4ad1-aac9-c73cc3816044.png)

Another correct representation, without the last HIT and the dropdown set to 2 squids:

![image](https://user-images.githubusercontent.com/11410900/144492526-4c5b3316-70a9-4386-b276-6a3bf1071f06.png)
