### ISSUE TITLE
Ability to save ship positions from suggested move board

### ISSUE THREAD

**Issue by csunday95** [petersn/web-sploosh-kaboom#9]
A useful time saving function would be the ability to transfer the ship position information from the top suggested move board to the latest ship position grid. This can be as simple as a button that appears once all ship positions have been determined. In cases where the ship positions may be ambiguous (e.g. 2 and 3 ship laid end to end), the button can be disabled with a notification that the board is ambiguous. In this case we can fall back on manual entry. 

credit for original idea to: @Kynsareth

**Comment by petersn** [comment]
This is implemented now, including automatic disambiguation using the RNG state sequence. That is to say, if you have some history boards inputted, and the hit pattern on the top board is ambiguous, but not ambiguous given the prior over where you are in the RNG sequence, it'll still copy successfully. I think this should make the situations where it's ambiguous and fails to copy pretty rare -- probably about 0.5% of cases that are normally ambiguous will fail to disambiguate this way.
